import axios from 'axios';
import AsyncStorage from '@react-native-async-storage/async-storage';

// Create an Axios instance
const api = axios.create({
	baseURL: process.env.EXPO_PUBLIC_API_BASE_URL,
	headers: {
		'Content-Type': 'application/json',
	},
});

// Add a request interceptor to include the JWT token in headers
api.interceptors.request.use(
	async (config) => {
		const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkwYzczYzM3LWQyYzgtNDA4Yy05MGEwLTFkMDBiYzNiNDBiYSIsImZpcnN0X25hbWUiOiJGb2xhIiwibGFzdF9uYW1lIjoiR2JhZGUiLCJtaWRkbGVfbmFtZSI6bnVsbCwiZW1haWwiOiJmb2xhZ2JhZGVAYmVsbGZhc3Qub3JnIiwiZW1haWxfdmFsaWQiOnRydWUsInBob25lX3ZhbGlkIjp0cnVlLCJwaG9uZV9udW1iZXIiOiIyMzQ4MDYzMjU5NjIxIiwiZ2VuZGVyIjoiZmVtYWxlIiwiZG9iIjoiMTk3NC0wNi0wMSIsInByb2ZpbGVfaW1hZ2UiOiJodHRwczovL3FtdXBydHVic2pwbnVyeGV1enl1LnN1cGFiYXNlLmNvL3N0b3JhZ2UvdjEvb2JqZWN0L3B1YmxpYy9QdWJsaWMtQnVja2V0L1Byb2ZpbGVfSW1hZ2UucG5nIiwiY3VzdG9tZXJfY29kZSI6IkNVU195aWwzZTBtN21ndWs5ZzMiLCJpZGNhcmRfbm8iOiI2MzE4NDg3NjIxMyIsImZhY2VfY2FwdHVyZSI6Imh0dHBzOi8vcW11cHJ0dWJzanBudXJ4ZXV6eXUuc3VwYWJhc2UuY28vc3RvcmFnZS92MS9vYmplY3QvcHVibGljL1B1YmxpYy1CdWNrZXQvbmluSW1hZ2UuanBnIiwiY291bnRyeSI6Ik5pZ2VyaWEiLCJzdGF0ZSI6Ik95byIsImNpdHkiOiJPZ2JvbW9zbyIsImhvbWVfYWRkcmVzcyI6IjU3MzMrNTQ1LCBTYWJvLCBPZ2JvbW9zbyAyMTIxMDIsIE95bywgTmlnZXJpYSIsImxhdGl0dWRlIjoiOC4xNTI3NTMzIiwibG9uZ2l0dWRlIjoiNC4yNTMxMzE3Iiwia3ljX3N0YXR1cyI6InZlcmlmaWVkIiwic3RhdHVzIjoiYWN0aXZlIiwicmVnX3N0cmF0ZWd5IjoiZW1haWwiLCJiYXNpY19pbmZvX3N0YXR1cyI6ImNvbXBsZXRlZCIsImRldmljZV90b2tlbiI6bnVsbCwicHVzaF9ub3RpZmljYXRpb25fc3RhdHVzIjpmYWxzZSwiY3JlYXRlZF9hdCI6IjIwMjUtMDEtMzBUMjA6MTY6MDMuMTA2WiIsIm90cF90aW1lc3RhbXAiOm51bGwsImRlbGV0ZWQiOmZhbHNlLCJpc19wZW5kaW5nX2RlbGV0ZSI6ZmFsc2UsInJvbGVzIjpbInVzZXIiLCJwcm92aWRlciJdLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MDI1MTg4MywiZXhwIjoxNzQwMjU0ODgzfQ.6b_oh8BDqPIANSEJn9AlV9qad6D0dRP_O96X6j2xDZE";
		if (token) {
			config.headers.Authorization = `Bearer ${token}`;
		}
		return config;
	},
	(error) => {
		return Promise.reject(error);
	}
);

export default api;